job: 
  type: aws
  streamName: testStream
  applicationName: testApplication
  region: ${AWS_DEFAULT_REGION}
  shardSize: 20
  jobPoolSize: 20
# Database settings.
database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver

  # the username
  user: sa

  # the password
  password: sa

  # the JDBC URL
  url: jdbc:h2:./target/example

# HTTP-specific options.
server: 
  applicationConnectors:
    - type: http
      port: 8000
      acceptQueueSize: 100
  adminConnectors:
    - type: http
      port: 8001

  # Maximum number of threads.
  maxThreads: 100

  # Minimum number of thread to keep alive.
  minThreads: 10

  # The maximum amount of time a connection is allowed to be idle before being closed.
  idleThreadTimeout: 1s

#  ssl:
#    keyStore: ./example.keystore
#    keyStorePassword: example
#
#    keyStoreType: JKS # (optional, JKS is default)

  # HTTP request log settings
  requestLog:
    # Settings for logging to stdout.
    appenders:
      - type: console

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  # Logger-specific levels.
  loggers:
    "com.github.wreulicke.dropwizard": INFO
    "com.amazonaws.services": DEBUG
    "org.eclipse.jetty": DEBUG
  # Settings for logging to stdout.
  appenders:
    - type: console
      threshold: INFO
      includeCallerData: true
      logFormat: "%d{yyyy/MM/dd HH:mm:ss.SSS,JST} [%.16thread] %-5level %logger{36}:%line - %msg%n"
