
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: localstack/localstack
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
          - v1-dependencies-

      - run: ./gradlew dependencies

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
        
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results/



